### PR TITLE
Allow global translations configuration

### PR DESCRIPTION
**Pull request by ivanovyordan**

### CODE REVIEW

**Comment by krivochenko** [comment]
What do you want to do this change for?

**Comment by ivanovyordan** [comment]
I am testing a translation module. This wold help me use one global configuration for all modules and I won't need to copy the configuration for your module.

**Comment by krivochenko** [comment]
But in with case my translations won't include always when there is another translations.

**Comment by ivanovyordan** [comment]
Exactly. I am using https://github.com/lajax/yii2-translate-manager which scans your module so I can translate it easily to Bulgarian.

**Pull request closed without merging**
