### PR TITLE
Fixed issue with bad table names (without table prefix)

### PR DESCRIPTION
**Pull request by BaBL86**
Fixed migration errors

### CODE REVIEW

**Comment by krivochenko** [comment]
Surry, but it was fixed earlier.

**Comment by BaBL86** [comment]
Are you sure? I don't see this code in master of this repo (check the end of up section, with inserts)

I create this request because after composer actual update I've got an errors in migration.

**Comment by budyaga** [comment]
https://github.com/budyaga/yii2-users/blob/master/migrations/m130524_201442_init.php

You should check in composer.lock which version do you use:

```
            "name": "budyaga/yii2-users",
            "version": "0.1.11",
```

**Comment by krivochenko** [comment]
Oh sorry. I think you mean table name in the command of its creation.

**Comment by krivochenko** [comment]
Thanks!

**Pull request merged**
